### ISSUE TITLE
Is VC1S supported at AMS1?

### ISSUE THREAD

**Issue by torinoronin** [stefanprodan/k8s-scw-baremetal#21] opened 2018-08-07 21:49 UTC
Is it possible to deploy k8s at VC1S instances?
```
terraform apply \
-var region=ams1 \
-var arch=x86_64 \
-var server_type=VC1S \
-var nodes=1 \
-var server_type_node=VC1S \
-var weave_passwd=fk43fnk%4$ \
-var docker_version=17.12.0-ce-0-ubuntu
provider.scaleway.organization
  The Organization ID (a.k.a. 'access key') for Scaleway API operations.

  Enter a value: XXXXXXXXXXXXXXXXXx

provider.scaleway.token
  The API key for Scaleway API operations.

  Enter a value: XXXXXXXXXXXXXXXXXXx

data.scaleway_image.xenial: Refreshing state...

Error: Error refreshing state: 1 error(s) occurred:

* data.scaleway_image.xenial: 1 error(s) occurred:

* data.scaleway_image.xenial: data.scaleway_image.xenial: The query returned more than one result. Please refine your query.

```

**Comment by justinclift** [comment] 2018-08-12 14:12
At a general thought, from the `The query returned more than one result. Please refine your query` bit it sounds like the problem is in the query not being specific enough, so more results were returned than can be handled.

You'll probably need to hit it with a debugger (or even add a `Println()` type of thing) to display the returned results so you can figure out what bit needs changing. :smile:

**Comment by stephenmoloney** [comment] 2019-01-06 19:03
I think this might work with a newer version of the terraform-scaleway-provider.

**Comment by stefanprodan** [comment] 2019-01-18 11:57
Closing this as it was a Scaleway Terraform provider bug and not related to this project.

**Closed by stefanprodan** 2019-01-18 11:57 UTC
