### ISSUE TITLE
"error: metrics not available yet"

### ISSUE THREAD

**Issue by yohannprigent** [stefanprodan/k8s-scw-baremetal#43] opened 2019-01-19 14:12 UTC
When I launch a cluster creation with the how to, I can't access the metrics :

```
kubectl --kubeconfig ./$(terraform output kubectl_config) \
  top nodes
error: metrics not available yet
```

It seems there is an issue visible on the dasboard : 

0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
<img width="1369" alt="screenshot 2019-01-19 at 15 11 36" src="https://user-images.githubusercontent.com/1750234/51427846-92327680-1bfc-11e9-998c-7a1954b9a74c.png">

**Comment by stephenmoloney** [comment] 2019-01-19 16:00
I just ran that command and there are no issues:

```
root@amd64-master-1:~# kubectl top nodes
NAME             CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
amd64-master-1   402m         10%    2090Mi          26%       
amd64-node-1     469m         11%    2245Mi          28%    
```

The cluster is up since yesterday.

Did you try again after 5 minutes or so?

Can you provide all the terraform variables except sensitve ones ?

**Comment by stephenmoloney** [comment] 2019-01-19 16:46
Ok, there is some issue on arm anyways - I haven't tested amd64. (I use metrics-server from helm on amd64 and that works but not tested this repo directly)

I've reproduced this error on arm as follows:

```
terraform apply \
  -var region=par1  \
  -var arch=arm  \
  -var server_type=C1  \
  -var nodes=1  \
  -var server_type_node=C1 \
  -var weave_passwd=ChangeMe  \
  -var docker_version=18.06 \
  -var ubuntu_version="Ubuntu Xenial"  \
  -var k8s_version=stable-1.13 \
  -var kubeadm_verbosity=4  \
  --auto-approve;
```

```
root@arm-master-1:~# kubectl top nodes
error: metrics not available yet
root@arm-master-1:~# kubectl get nodes -o wide
NAME           STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION          CONTAINER-RUNTIME
arm-master-1   Ready    master   21m     v1.13.2   10.1.36.104   <none>        Ubuntu 16.04.5 LTS   4.4.127-mainline-rev1   docker://18.6.1
arm-node-1     Ready    <none>   2m9s    v1.13.2   10.1.20.235   <none>        Ubuntu 16.04.5 LTS   4.4.127-mainline-rev1   docker://18.6.1
arm-node-2     Ready    <none>   2m39s   v1.13.2   10.1.20.192   <none>        Ubuntu 16.04.5 LTS   4.4.127-mainline-rev1   docker://18.6.1
arm-node-3     Ready    <none>   15m     v1.13.2   10.1.20.201   <none>        Ubuntu 16.04.5 LTS   4.4.127-mainline-rev1   docker://18.6.1
```

**Comment by stephenmoloney** [comment] 2019-01-19 22:34
I've a fix for this. It was a change I had made to my own fork but forgot to make a PR here.

- The RBAC rules need to be updated
- *I think* kubelet webhook authentication is meant to be activated

It's a bit of a temp fix really, I'll make a PR soon.

**Comment by yohannprigent** [comment] 2019-01-19 23:09
I did not see your reply on time, but if you need anything from me to help you, tell me ! As you’ve reproduced I don’t think you need the variables anymore.

**Comment by stephenmoloney** [comment] 2019-01-19 23:33
@stefanprodan  ref #44  - eventually a longer term fix without `insecure=true` should be sought. 

There seems be some issue with the certs and metrics-server and kubelet.

This issue and this comment is relevant
github: `/kubernetes-incubator/metrics-server/issues/133#issuecomment-424090916`

**Comment by stephenmoloney** [comment] 2019-01-19 23:34
@yohannprigent #44  should have metrics server working for time being - although it's not a long term solution really.

**Closed** 2019-01-20 09:20 UTC
